repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.10.0
  #   hooks:
  #     - id: mypy

  # - repo: https://github.com/PyCQA/pylint
  #   rev: v3.1.0
  #   hooks:
  #     - id: pylint
  #       args: ["--disable=R,C"]  # Opcional: ignora avisos de naming/convention

  # - repo: local
  #   hooks:
  #     - id: vulture
  #       name: vulture
  #       entry: vulture .
  #       language: system  # Usa o vulture instalado no sistema/venv
  #       types: [python]
